
package insurance;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Insurance", targetNamespace = "http://insurance/", wsdlLocation = "http://localhost:8083/insurance/Insurance?wsdl")
public class Insurance_Service
    extends Service
{

    private final static URL INSURANCE_WSDL_LOCATION;
    private final static WebServiceException INSURANCE_EXCEPTION;
    private final static QName INSURANCE_QNAME = new QName("http://insurance/", "Insurance");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/insurance/Insurance?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSURANCE_WSDL_LOCATION = url;
        INSURANCE_EXCEPTION = e;
    }

    public Insurance_Service() {
        super(__getWsdlLocation(), INSURANCE_QNAME);
    }

    public Insurance_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSURANCE_QNAME, features);
    }

    public Insurance_Service(URL wsdlLocation) {
        super(wsdlLocation, INSURANCE_QNAME);
    }

    public Insurance_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSURANCE_QNAME, features);
    }

    public Insurance_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Insurance_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Insurance
     */
    @WebEndpoint(name = "InsurancePort")
    public Insurance getInsurancePort() {
        return super.getPort(new QName("http://insurance/", "InsurancePort"), Insurance.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Insurance
     */
    @WebEndpoint(name = "InsurancePort")
    public Insurance getInsurancePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://insurance/", "InsurancePort"), Insurance.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSURANCE_EXCEPTION!= null) {
            throw INSURANCE_EXCEPTION;
        }
        return INSURANCE_WSDL_LOCATION;
    }

}
