
package insurance;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Insurance", targetNamespace = "http://insurance/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Insurance {


    /**
     * 
     * @param date
     * @param physicianId
     * @param patientId
     * @param price
     * @param medicalServiceId
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "redeemMedicalService", targetNamespace = "http://insurance/", className = "insurance.RedeemMedicalService")
    @ResponseWrapper(localName = "redeemMedicalServiceResponse", targetNamespace = "http://insurance/", className = "insurance.RedeemMedicalServiceResponse")
    @Action(input = "http://insurance/Insurance/redeemMedicalServiceRequest", output = "http://insurance/Insurance/redeemMedicalServiceResponse")
    public int redeemMedicalService(
        @WebParam(name = "physicianId", targetNamespace = "")
        int physicianId,
        @WebParam(name = "patientId", targetNamespace = "")
        int patientId,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "medicalServiceId", targetNamespace = "")
        int medicalServiceId,
        @WebParam(name = "price", targetNamespace = "")
        double price);

}
