
package order;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Order", targetNamespace = "http://order/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Order {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://order/", className = "order.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://order/", className = "order.GetNameResponse")
    @Action(input = "http://order/Order/getNameRequest", output = "http://order/Order/getNameResponse")
    public String getName();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDescription", targetNamespace = "http://order/", className = "order.GetDescription")
    @ResponseWrapper(localName = "getDescriptionResponse", targetNamespace = "http://order/", className = "order.GetDescriptionResponse")
    @Action(input = "http://order/Order/getDescriptionRequest", output = "http://order/Order/getDescriptionResponse")
    public String getDescription();

    /**
     * 
     * @param reservationId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelReservation", targetNamespace = "http://order/", className = "order.CancelReservation")
    @ResponseWrapper(localName = "cancelReservationResponse", targetNamespace = "http://order/", className = "order.CancelReservationResponse")
    @Action(input = "http://order/Order/cancelReservationRequest", output = "http://order/Order/cancelReservationResponse")
    public boolean cancelReservation(
        @WebParam(name = "reservationId", targetNamespace = "")
        int reservationId);

    /**
     * 
     * @return
     *     returns java.util.List<order.MedicalSupply>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMedicalSupplies", targetNamespace = "http://order/", className = "order.GetMedicalSupplies")
    @ResponseWrapper(localName = "getMedicalSuppliesResponse", targetNamespace = "http://order/", className = "order.GetMedicalSuppliesResponse")
    @Action(input = "http://order/Order/getMedicalSuppliesRequest", output = "http://order/Order/getMedicalSuppliesResponse")
    public List<MedicalSupply> getMedicalSupplies();

    /**
     * 
     * @param reservationId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeOrder", targetNamespace = "http://order/", className = "order.MakeOrder")
    @ResponseWrapper(localName = "makeOrderResponse", targetNamespace = "http://order/", className = "order.MakeOrderResponse")
    @Action(input = "http://order/Order/makeOrderRequest", output = "http://order/Order/makeOrderResponse")
    public boolean makeOrder(
        @WebParam(name = "reservationId", targetNamespace = "")
        int reservationId);

    /**
     * 
     * @param reservationId
     * @param medicalSupplyQuantity
     * @param manufacturerId
     * @param medicalSupplyName
     * @return
     *     returns order.Offer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeReservation", targetNamespace = "http://order/", className = "order.MakeReservation")
    @ResponseWrapper(localName = "makeReservationResponse", targetNamespace = "http://order/", className = "order.MakeReservationResponse")
    @Action(input = "http://order/Order/makeReservationRequest", output = "http://order/Order/makeReservationResponse")
    public Offer makeReservation(
        @WebParam(name = "reservationId", targetNamespace = "")
        int reservationId,
        @WebParam(name = "manufacturer_id", targetNamespace = "")
        String manufacturerId,
        @WebParam(name = "medicalSupplyName", targetNamespace = "")
        String medicalSupplyName,
        @WebParam(name = "medicalSupplyQuantity", targetNamespace = "")
        int medicalSupplyQuantity);

    /**
     * 
     * @param reservationId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://order/", className = "order.CancelOrder")
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://order/", className = "order.CancelOrderResponse")
    @Action(input = "http://order/Order/cancelOrderRequest", output = "http://order/Order/cancelOrderResponse")
    public boolean cancelOrder(
        @WebParam(name = "reservationId", targetNamespace = "")
        int reservationId);

}
